---
# install dependencies needed to build/run the docker lxc engine (http://www.docker.io/)
# Basically a reworking of docker's Vagrentfile[1] into an ansible-playbook
# [1] https://github.com/dotcloud/docker/blob/master/Vagrantfile
 
### PPA install ###
- name: Enable ppa adding via apt-add-repository is available
  tags: ppa,dev
  apt: pkg={{ item }} state=latest
  with_items: {{ docker_deps }} # defined in groupvars/hosting.yml
  
- name: Add docker ppa
  tags: ppa
  apt_repository: repo=ppa:dotcloud/lxc-docker

- name: Install docker via ppa
  tags: ppa
  apt: pkg=lxc-docker state=latest update_cache=yes

  
### Dev Install ###
- name: Install docker development dependencies
  tags: dev
  apt: pkg={{ item }} state=latest update_cache=yes
  with_items: docker_dev_deps # defined in groupvars/hosting_dev.yml

# TODO: improve granularity of this checking, i.e. version number, cloning only if absent
- name: Clone docker via git
  tags: dev
  git: repo={{docker_git_url}} dest=/tmp/docker/

- name: Docker dev make, make install
  tags: dev
  shell: cd /tmp/docker && make && cp ./bin/docker /usr/local/bin/docker

- name: Determine if docker is installed already
  tags: dev
  debug: msg="docker installed at:{{item}}"
  with_lines:
    - which docker


      
