---
# Install the required kernel for docker

- name: Install linux-image-{{ linux_kernel }} # defined in group_vars/hosting.yml
  tags: dep,ppa,bin
  apt: package=linux-image{{ linux_kernel }} update_cache=yes

- name: Install wget
  tags: vbox
  apt: package=wget state=latest

- name: wget iso
  tags: vbox
  action: wget -q {{ vbox_additions_iso }}


