---
# Install the required kernel for docker

- name: Install suggested kernel
  tag: dep,ppa,bin
  apt: package={{ linux_kernel }} # defined in group_vars/hosting.yml

- name: Install wget
  tag: vbox
  apt: package=wget state=latest

- name: wget iso
  tag: vbox
  action: wget -q {{ vbox_additions_iso }}


